### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by asdforwarder** [sxhatrix/bawt#12]
You should be able to open up issues from Discord like: https://github.com/LeagueSandbox/IssueBot/

**Comment by asdforwarder** [comment]
@boveus @sxhatrix

**Comment by boveus** [comment]
Looks like we can accomplish this with the GitHub API: https://developer.github.com/v3/issues/#create-an-issue

**Comment by boveus** [comment]
I don't know how useful it would be to use chat to open an issue on GH, since the entire purpose of discord is text-based chat.  We could probably just discuss new features in chat rather than opening a new issue via a chat command.
