### ISSUE TITLE
Clean up breaking news

### ISSUE THREAD

**Issue by carsonwilliamsdev** [sxhatrix/bawt#5]
Breaking news currently outputs as such:

BREAKING NEWS ALERT MESSAGE
article title
[random giphy gif]

Often times multiple news articles are uploaded at once so we get bursts of 5 alerts all at once. When this happens it should look like this:

BREAKING NEWS ALERT MESSAGE
[random giphy gif]
article title
article title
article title
article title

If nothing has been posted for the past 5 minutes it should report the news alert message and the gif. I also think the title should be a link to the article.

**Comment by boveus** [comment]
#7 addresses this
